import array as arr
a = arr.array('i', [5, 6, 8, 78, 98, 23, 65, 43, 6, 6])
print('Array:', a)
a.insert(3, 37)
print('Updated Array:', a)
a.append(98)
print('Updated Array:', a)
a.remove(78)
print('Updated Array:', a)
a.pop()
print('Updated Array:', a)
print('Index of 23:', a.index(23))
print('Count of 6:', a.count(6))
a.reverse()
print('Reversed Array:', a)